name = "Jkrebian"
license = "MIT"
licenselink = "https://github.com/jkrebian/neocities/blob/master/LICENSE"
description = "Project Neocities."
homepage = "https://github.com/jkrebian/neocities/"
tags = ["personal","timeline","feed","mobile","light","dark","dark mode","customizable","plausible"]
features = ["timeline","neocities","custom css","rss","json"]
min_version = "0.41.0"

[author]
  name = "John Krebian"
  homepage = "https://jkrebian.neocities.org/"
