baseURL = "https://jkrebian.neocities.org/"
languageCode = "en-us"
title = "Jkrebian"
paginate = 10

[taxonomies]
tag = "tags"

[author]
name = "John Krebian" # Your online name
# Your profile image. External link or relative to static/. Examples:
# "https://imgur.com/123456788"
# "image/me.webp"
image = ""
about = "I'm dreaming, I'm dreaming! Come on, wake up! Wake up! Wake up..."

[params]
skin = "macintosh"

# socialImage = "static/img/social.png" # site image for rich embeds
# customCSS = "css/style.css" # relative to ./static/
# plausible = true
# webmentionUrl = "https://webmention.io/example/webmention"
# pingbackUrl = "https://webmention.io/example/xmlrpc"
# micropubUrl = "https://example.com/.netlify/functions/micropub"
# microsubUrl = "https://aperture.p3k.io/microsub/example"

# For IndieAuth and the author card
githubuser = "jkrebian"
twitteruser = "jkrebian" # no @ in front
mastodon = "https://mstdn.plus/@jkrebian" # full link to your instance profile

[permalinks]
# Format for feed entry links. You probably don't need to change this.
feed = "/:title/"

[outputs]
# Output formats for your feed. You probably don't need to change this.
  home = ["HTML", "JSON", "RSS"]
